---
- name: user module demo
  hosts: all
  become: true
  vars:
    myuser: "User present "
  tasks:
    - name: disable user
      ansible.builtin.user:
        name: "{{ myuser }}"
        state: present
        password_lock: true
        shell: "/sbin/nologin"
