---
- name: extract an archive 
  hosts: all
  become: "false"
  vars: 
    myurl: "https://github.com/lucab85/ansible-pilot/archive/refs/heads/master.zip"

  tasks: 
    - name: extractpr presents
      ansible.builtin.yum:
        name:
          - unzip
          - tar
        state: present 
      become: "true"

    - name: extract archive
      ansible.builtin.unarchive:
        src: "{{ mysrc }}"
        dest: "/home/devops/"
        remote_src: "true"
        validate_certs: "true"
             


