---
- name: check if file exists
  hosts: all
  become: "false"
  vars:
    myfile: ~/test.txt
  tasks: 
    - name: check if a file exists
      ansible.builtin.stat:
        path: "{{ myfile }}"  
      register: file_data

    - name: report file exists
      ansible.builtin.debug:
       msg: "The file {{ myfile }} exists duh!!"
      when: file_data.stat.exists

    - name: Report if the file does not exist
      ansible.builtin.debug:
        msg: "The file {{ myfile }} doesn't exist dawg"
      when: file_data.stat.exists       
