---
- name: git module demo
  hosts: all
  vars:
    repo: "git@github.com:JEgg96/Ansible-Playbook-Examples.git"
    dest: "/home/devops/ansible-pilot"
    sshkey: "~/.ssh/id_rsa"
  tasks:
    - name: ensure git pkg installed
      ansible.builtin.yum:
        name: git
        state: present
        update_cache: true
      become: true

    - name: checkout git repo
      ansible.builtin.git:
        repo: "{{ repo }}"
        dest: "{{ dest }}"
        key_file: "{{ sshkey }}"
        
# Please create an EC2 instance for free with the key pair installed in order to see the change on your instance either wise you will get an error
# like this: fatal: [localhost]: FAILED! => {"changed": false, "msg": ["Could not detect which major revision of yum is in use, which is required to determine module backend.", 
# "You should manually specify use_backend to tell the module whether to use the yum (yum3) or dnf (yum4) backend})"]}
