---
- name: handler demo
  hosts: all
  tasks:
     - name: changed status 
       ansible.builtin.command: "uptime"
       notify: 
        - message 1
        - message 2
       
  handlers:
    - name: message 1
      ansible.builtin.debug:
        msg: message 1

    - name: message 2
      ansible.builtin.debug:
        msg: message 2
      listen: message  
# Able to run two different handlers on a playbook!