---
- name: service module demo 
  hosts: all
  become: "true" 
  vars:
    services_on_boot:
      - "chronyd.service"
    tasks:
      - name: populate ansible facts
        ansible.builtin.service_facts:

      - name: enable services on boot
        ansible.builtin.service:
          - name: " {{ item }}"
            enabled: "true"
            state: started
        when: "item in services"   
        with_items: ' {{ services_on_boot }}'
