---
- name: command module demo 
  hosts: all
  tasks: 
    - name: check uptime
      ansible.builtin.command: uptime 
      register: command_output

    - name: command_output
      ansible.builtin.debug:
        var: command_output.stdout_lines
