---
- name: user module demo
  hosts: all
  become: true
  tasks:
    - name: user example not present
      ansible.builtin.user:
        name: User present 
        state: "absent"
        remove: true
