---
- name: user password demo
  hosts: all
  become: true
  vars:
    myuser: "User present "
    mypassword: "password"
  tasks:
    - name: change password
      ansible.builtin.user:
        name: "{{ myuser }}"
        state: present
        password: "{{ mypassword | password_hash('sha512') }}"
